version: '3.7'

networks:
  default:
    driver: bridge

services:
  mysql:
    image: mysql:5.7
    container_name: cluster_rumah_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cluster_rumah
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - default
